#! /bin/sh
#
# Sample events script for mcabber
# Use awesome naughty  to display events on the user's desktop
#
# To use this script, set the "events_command" option to the path of
# the script (see the mcabberrc.example file for an example)
#

export event=$1
export arg1=$2
export arg2=$3
export filename=$4
# Note that the 4th argument is only provided for incoming messages
# and when 'event_log_files' is set.

if [ $event = "MSG" ]; then
  case "$arg1" in
    IN)
      # Incoming message from buddy $arg2
#      echo "You have an IM from <$arg2>" | $XOSD_CMD_PIPE > /dev/null 2>&1
echo "naughty.notify({title = 'mcabber', text = 'You have an IM from $arg2', timeout = 10})" | awesome-client -
#      if [ -n "$filename" -a -f "$filename" ]; then
        # We could process filename here...
        /bin/rm $filename
#      fi
      ;;
    MUC)
      # Groupchat message in room $arg2
      if [ -n "$filename" && -f "$filename" ]; then
        # We could process filename here...
        /bin/rm $filename
      fi
      ;;
    OUT)
      # Outgoing message for buddy $arg2
      ;;
  esac
elif [ $event = "STATUS" ]; then
  # Buddy $arg2 status is $arg1 (_, O, I, F, D, N, A)
 echo "naughty.notify({title = 'mcabber', text ='$arg2  status $arg1', timeout = 10})" | awesome-client -
fi

